<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DessertsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('desserts')->insert([
            [
                'name' => 'Шоколадный торт',
                'category' => 'Торт',
                'description' => 'Нежный шоколадный бисквит с кремом',
                'price' => 450.00,
                'photos' => null,
                'available' => true,
                'weight' => 500,
                'calories' => 250,
                'proteins' => 5.5,
                'fats' => 12.0,
                'carbohydrates' => 30.0,
            ],
            [
                'name' => 'Чизкейк Нью-Йорк',
                'category' => 'Торт',
                'description' => 'Классический сливочный чизкейк',
                'price' => 500.00,
                'photos' => null,
                'available' => true,
                'weight' => 450,
                'calories' => 320,
                'proteins' => 6.0,
                'fats' => 15.0,
                'carbohydrates' => 35.0,
            ],
            [
                'name' => 'Наполеон',
                'category' => 'Торт',
                'description' => 'Слоёный торт с кремом',
                'price' => 400.00,
                'photos' => null,
                'available' => true,
                'weight' => 400,
                'calories' => 300,
                'proteins' => 5.0,
                'fats' => 14.0,
                'carbohydrates' => 32.0,
            ],
            [
                'name' => 'Эклер',
                'category' => 'Пирожное',
                'description' => 'Пирожное с заварным кремом',
                'price' => 120.00,
                'photos' => null,
                'available' => true,
                'weight' => 80,
                'calories' => 180,
                'proteins' => 3.0,
                'fats' => 8.0,
                'carbohydrates' => 22.0,
            ],
            [
                'name' => 'Макарон',
                'category' => 'Пирожное',
                'description' => 'Французское миндальное печенье с кремом',
                'price' => 100.00,
                'photos' => null,
                'available' => true,
                'weight' => 30,
                'calories' => 120,
                'proteins' => 2.0,
                'fats' => 5.0,
                'carbohydrates' => 18.0,
            ],
            [
                'name' => 'Медовик',
                'category' => 'Торт',
                'description' => 'Слоёный медовый торт с кремом',
                'price' => 380.00,
                'photos' => null,
                'available' => true,
                'weight' => 450,
                'calories' => 280,
                'proteins' => 5.0,
                'fats' => 12.0,
                'carbohydrates' => 34.0,
            ],
            [
                'name' => 'Капкейк',
                'category' => 'Пирожное',
                'description' => 'Маленький кекс с кремовой начинкой',
                'price' => 90.00,
                'photos' => null,
                'available' => true,
                'weight' => 70,
                'calories' => 150,
                'proteins' => 2.0,
                'fats' => 6.0,
                'carbohydrates' => 20.0,
            ],
            [
                'name' => 'Тирамису',
                'category' => 'Торт',
                'description' => 'Итальянский десерт с маскарпоне и кофе',
                'price' => 480.00,
                'photos' => null,
                'available' => true,
                'weight' => 400,
                'calories' => 310,
                'proteins' => 6.0,
                'fats' => 14.0,
                'carbohydrates' => 32.0,
            ],
            [
                'name' => 'Павлова',
                'category' => 'Торт',
                'description' => 'Меренговый десерт с ягодами и сливками',
                'price' => 450.00,
                'photos' => null,
                'available' => true,
                'weight' => 350,
                'calories' => 270,
                'proteins' => 4.0,
                'fats' => 10.0,
                'carbohydrates' => 35.0,
            ],
            [
                'name' => 'Сметанник',
                'category' => 'Торт',
                'description' => 'Сметанный торт со слоёным тестом',
                'price' => 370.00,
                'photos' => null,
                'available' => true,
                'weight' => 400,
                'calories' => 260,
                'proteins' => 5.0,
                'fats' => 12.0,
                'carbohydrates' => 30.0,
            ],
        ]);
    }
}
